import { useEffect, useState } from 'react'
import FadeImage from '../components/FadeImage'

function TrainCardSkeleton() {
  return (
    <div className="train-card">
      <div className="skeleton" style={{ aspectRatio: '4/3' }} />
      <div className="cap"><div className="skel-line" style={{ width: '80%' }} /></div>
    </div>
  )
}

export default function TrainingPage() {
  const [samples, setSamples] = useState(null)
  const [showOverlay, setShowOverlay] = useState(true)

  useEffect(() => {
    fetch('/api/training-samples').then(r => r.json()).then(setSamples)
  }, [])

  return (
    <div className="content">
      <div className="page-head">
        <div className="stamp">EXHIBIT B</div>
        <h1 className="headline">Training data — CutMix outlier exposure</h1>
        <p className="lede">
          What the OOD heads actually trained on: real Cityscapes street frames with COCO object cutouts
          pasted onto the road (<span className="mono">data/cutmix.py</span>), sized like real lost cargo and
          colour-matched to the road they land on. The blue highlight is the mask the heads were told counts as
          anomalous. Every Cityscapes-known category (car, person, bus…) is removed from the COCO bank, so the model
          is never taught that cars are anomalies. These 8 are generated by the same code from the validation split
          with a fixed seed. The earlier CARLA frames are not used: 23 of 45 had misaligned masks.
        </p>
      </div>

      {!samples ? (
        <>
          <div className="skel-line" style={{ width: 200, height: 34, marginBottom: 16 }} />
          <div className="train-grid">
            {Array.from({ length: 8 }).map((_, i) => <TrainCardSkeleton key={i} />)}
          </div>
        </>
      ) : (
        <>
          <button className="toggle-btn" onClick={() => setShowOverlay(v => !v)}>
            {showOverlay ? 'SHOWING: MASK OVERLAY' : 'SHOWING: RAW FRAME'} — CLICK TO TOGGLE
          </button>
          <div className="train-grid">
            {samples.map(s => (
              <div className="train-card" key={s.id}>
                <FadeImage
                  key={showOverlay ? 'overlay' : 'raw'}
                  src={showOverlay ? s.panels.overlay : s.panels.raw}
                  alt={s.source_file}
                />
                <div className="cap"><div className="t mono">{s.source_file}</div></div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  )
}
